# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    name: Building for ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Create Build dir
      run: mkdir build

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build jem
      run: go build -o ../build/. -v ./...
      working-directory: jem

    - name: Test jem
      run: go test -v ./...
      working-directory: jem
      
    - name: Build jem-install
      run: go build -o ../build/. -v ./...
      working-directory: jem-install

    - name: Test jem-install
      run: go test -v ./...
      working-directory: jem-install
      
    - name: Build jem-uninstall
      run: go build -o ../build/. -v ./...
      working-directory: jem-uninstall

    - name: Test jem-uninstall
      run: go test -v ./...
      working-directory: jem-uninstall
      
    - name: Copy important files
      run: |
            cp ./LICENSE ./build/LICENSE
            cp ./README.md ./build/README.md
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: jem-${{ matrix.os }}
        path: ./build
        retention-days: 5
