name: Publish Release
on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    runs-on: ${{ matrix.os }}
    name: Create Release for ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Create Build dir
      run: mkdir build

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build jem
      run: go build -o ../build/. -v ./...
      working-directory: jem

    - name: Test jem
      run: go test -v ./...
      working-directory: jem
      
    - name: Build jem-install
      run: go build -o ../build/. -v ./...
      working-directory: jem-install

    - name: Test jem-install
      run: go test -v ./...
      working-directory: jem-install
      
    - name: Build jem-uninstall
      run: go build -o ../build/. -v ./...
      working-directory: jem-uninstall

    - name: Test jem-uninstall
      run: go test -v ./...
      working-directory: jem-uninstall
      
    - name: Copy important files
      run: |
            cp ./LICENSE ./build/LICENSE
            cp ./README.md ./build/README.md
            
    - uses: vimtor/action-zip@v1
      with:
        files: build/
        dest: jem-${{ matrix.os }}.zip
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: jem-${{ matrix.os }}.zip

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: build
