name: Publish Release
on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    runs-on: ${{ matrix.os }}
    name: Create Release for ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
     - uses: actions/download-artifact@v3
       with:
        name: jem-${{ matrix.os }}
        path: ~/download/

     - name: Display structure of downloaded files
       run: ls -R
       working-directory: ~/download/
